version: '3.8'
services:
  postgres:
    networks:
      - task_app_network
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    container_name: task_db
    hostname: task_db
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      DB_HOST: ${DB_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  task_app:
    networks:
      - task_app_network
    restart: unless-stopped
    container_name: task_app
    hostname: task_app
    build:
      context: .
      dockerfile: ./docker/task_app/Dockerfile
      target: dev
    depends_on:
      - postgres
      - redis
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
      HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      HTTP_PORT: ${HTTP_PORT}
      HTTPS_PORT: ${HTTPS_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PW: ${POSTGRES_PW}
      POSTGRES_DB: ${POSTGRES_DB}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      SALT_ROUNDS: ${SALT_ROUNDS}
    ports:
      - '${HTTP_PORT}:${HTTP_PORT}'
      - '${HTTPS_PORT}:${HTTPS_PORT}'
    volumes:
      - ./src:/usr/src/task_manager/src
  redis:
    networks:
      - task_app_network
    container_name: redis
    hostname: ${REDIS_HOST}
    image: redis:latest
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
networks:
  task_app_network:
    driver: bridge